name: Build and Publish image to Dockerhub
on:
  push:
    branches:
      - master

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Image
        run: docker compse build