name: Build and Publish image to Dockerhub
on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build . --file MinimalApiDocker/Dockerfile --tag detorresrc/minimalapi:latest

      - name: Login to Dockerhub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Image
        run: docker push detorresrc/minimalapi:latest